'use strict';

/**
 * Generates the "skill-library" router skill used by the personal setup.
 *
 * The router keeps the full ECC catalog out of Claude's context: SKILL.md is a
 * short page that says where the library lives and lists skill names by group,
 * and INDEX.md holds one line per skill (with its description) for keyword
 * search. Claude reads a library skill only when a task needs it.
 *
 * Used by scripts/personal-setup.js. See docs/PERSONAL-SETUP.md.
 */

const fs = require('fs');
const path = require('path');
const { parseFrontmatter } = require('./agent-compress');

const MAX_INDEX_DESCRIPTION = 240;

const ROUTER_DESCRIPTION = 'Find and load a specialised ECC skill on demand when no installed skill covers the task, '
  + 'for example another language or framework, video or media work, web research, scraping, security audits, '
  + 'DevOps, machine learning, content and marketing, or business operations. '
  + 'Use before improvising a multi-step workflow from scratch.';

function shorten(text, max) {
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  return `${(lastSpace > max / 2 ? cut.slice(0, lastSpace) : cut).replace(/[\s,;.]+$/, '')}...`;
}

function readSkillDescription(skillDir) {
  try {
    const { frontmatter } = parseFrontmatter(fs.readFileSync(path.join(skillDir, 'SKILL.md'), 'utf8'));
    let description = typeof frontmatter.description === 'string' ? frontmatter.description.trim() : '';
    if (description.length > 1 && description.startsWith("'") && description.endsWith("'")) {
      description = description.slice(1, -1);
    }
    return description.replace(/\s+/g, ' ');
  } catch {
    return '';
  }
}

function readModules(libraryRoot) {
  try {
    const manifest = JSON.parse(fs.readFileSync(path.join(libraryRoot, 'manifests', 'install-modules.json'), 'utf8'));
    return Array.isArray(manifest.modules) ? manifest.modules : [];
  } catch {
    return [];
  }
}

/**
 * Group every skill in the library by the install module that ships it.
 * Skills that no module lists go into an "other" group.
 */
function listSkillGroups(libraryRoot) {
  const skillsDir = path.join(libraryRoot, 'skills');
  const available = new Set(
    fs.readdirSync(skillsDir, { withFileTypes: true })
      .filter(entry => entry.isDirectory() && fs.existsSync(path.join(skillsDir, entry.name, 'SKILL.md')))
      .map(entry => entry.name)
  );
  const assigned = new Set();
  const groups = [];

  for (const mod of readModules(libraryRoot)) {
    const names = (mod.paths || [])
      .filter(item => typeof item === 'string' && item.startsWith('skills/'))
      .map(item => item.slice('skills/'.length).replace(/\/$/, ''))
      .filter(name => available.has(name) && !assigned.has(name));
    if (names.length === 0) continue;
    names.forEach(name => assigned.add(name));
    groups.push({ id: mod.id, description: mod.description || '', skills: names.sort() });
  }

  const other = [...available].filter(name => !assigned.has(name)).sort();
  if (other.length > 0) groups.push({ id: 'other', description: 'Skills not assigned to an install module.', skills: other });
  return groups;
}

function buildSkillLibraryRouter({ libraryRoot, exclude = [] }) {
  const excluded = new Set(exclude);
  const groups = listSkillGroups(libraryRoot)
    .map(group => ({ ...group, skills: group.skills.filter(name => !excluded.has(name)) }))
    .filter(group => group.skills.length > 0);
  const count = groups.reduce((total, group) => total + group.skills.length, 0);
  const skillPath = path.join(libraryRoot, 'skills', '<skill-name>', 'SKILL.md');
  const setupScript = path.join(libraryRoot, 'scripts', 'personal-setup.js');

  const skillMd = [
    '---',
    'name: skill-library',
    `description: ${ROUTER_DESCRIPTION}`,
    '---',
    '',
    '# Skill Library',
    '',
    'Generated by `scripts/personal-setup.js` from the ECC checkout below. Do not edit by hand;',
    're-run `node scripts/personal-setup.js global` after pulling updates.',
    '',
    `- Library: \`${libraryRoot}\``,
    `- Skills available on demand: ${count} (skills in the global core are not listed)`,
    '',
    '## How to use',
    '',
    '1. If an installed skill already fits the task, use it and stop here.',
    '2. Otherwise pick candidates from the groups below. To compare them, search `INDEX.md` in this',
    '   folder (one line per skill with its description) instead of opening many skills.',
    `3. Read \`${skillPath}\` for the chosen skill and follow it for the current task only.`,
    '   Open files next to it only when the skill refers to them.',
    '4. Do not copy library skills into the project. If the same library skill keeps being needed in one',
    `   project, suggest: \`node "${setupScript}" apply "<project folder>" --with <skill-name>\``,
    '5. If nothing fits, say so briefly and continue without a library skill.',
    '',
    '## Groups',
    '',
    ...groups.flatMap(group => [
      `### ${group.id} (${group.skills.length})`,
      '',
      ...(group.description ? [group.description, ''] : []),
      group.skills.join(', '),
      '',
    ]),
  ].join('\n');

  const indexMd = [
    '# Skill Library Index',
    '',
    'One line per skill: name, group, description. Search this file by keyword.',
    '',
    ...groups.flatMap(group => group.skills.map(name => {
      const description = shorten(readSkillDescription(path.join(libraryRoot, 'skills', name)), MAX_INDEX_DESCRIPTION);
      return `- \`${name}\` [${group.id}]: ${description || '(no description)'}`;
    })),
    '',
  ].join('\n');

  return { files: { 'SKILL.md': skillMd, 'INDEX.md': indexMd }, count, groups: groups.length };
}

module.exports = {
  buildSkillLibraryRouter,
  listSkillGroups,
  readSkillDescription,
  shorten,
};
